target "Aeda" do

pod 'TBXML', '~> 1.5'
pod 'TBXML+NSDictionary', '~> 0.0'
pod 'Reachability', '~> 3.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'GCPlaceholderTextView', '~> 1.0'
pod 'AFNetworking', '~> 2.3'
pod 'PDKeychainBindingsController', '~> 0.0'

end